---
os: linux
dist: focal
language: python
cache: pip
services:
  - docker

install:
  - pip3 install -U ansible jq docker
  - printf "[defaults]\nroles_path = ../" > ansible.cfg

script:
  - ansible-playbook tests/create.yml --syntax-check
  - ls -la /sys/fs/cgroup
  - docker run --rm --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name ubuntu ubuntu /sbin/init
  - yes | ansible-playbook tests/create.yml --connection=local
  - >
    result=$(yes | ansible-playbook tests/create.yml --connection=local);
    echo "$result" | grep -q 'changed=0.*failed=0'
    && (echo -e "Idempotence test: ${GREEN}pass${NC}"; exit 0)
    || (echo -e "Idempotence test: ${RED}fail${NC}"; echo -e "$result"; exit 1);
  - yes | ansible-playbook tests/destroy.yml --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
