---
os: linux
dist: focal
language: python
python:
  - "3.9"
cache: pip
services:
  - docker

install:
  - pip3 install -U ansible ansible-lint jq docker molecule molecule-docker

before_script:
  - molecule lint

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
