---
- name: Ensure work directory exists
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    mode: "0755"

- name: Generate SSH key
  ansible.builtin.shell: >
    if [ ! -r "{{ work_dir + '/' + ssh_keyfile }}" ]; then
      ssh-keygen -q -N "" -f {{ work_dir + '/' + ssh_keyfile }} -C {{ ssh_keyname }} || exit 1
      echo "done"
    fi
  register: ssh_key
  changed_when: ssh_key.stdout == "done"

- name: Slurp public key
  ansible.builtin.slurp:
    src: "{{ work_dir + '/' + ssh_keyfile }}.pub"
  register: ssh_key_pub

- name: Build and create containers
  ansible.builtin.include_tasks:
    file: create_container.yml
  vars:
    container: "{{ outer_container }}"
  with_items: "{{ containers }}"
  loop_control:
    loop_var: "outer_container"

- name: Generate docker inventory
  ansible.builtin.copy:
    dest: "{{ work_dir }}/docker_inventory"
    mode: "0644"
    content: |
      all:
        hosts:
      {% for container in container_inventory %}
          {{ container.name }}:
            ansible_connection: docker
      {% endfor %}
