---
- name: Check for required packages
  ansible.builtin.shell: >
    pip3 || echo "pip3 missing";
    ssh -G localhost || echo "openssh-client missing";
    python3 -c 'import setuptools' || echo "setuptools python library missing";
    python3 -c 'import docker' || echo "docker python library missing";
  register: required_packages
  changed_when: false
  failed_when: "'missing' in required_packages.stdout"
