---
- name: Stop virtual machine
  community.libvirt.virt:
    command: stop
    name: "{{ instance.name }}"
    state: shutdown
  become: true
  become_user: root
  failed_when: false

- name: Delete virtual machine
  community.libvirt.virt:
    command: undefine
    name: "{{ instance.name }}"
  become: true
  become_user: root
  failed_when: false

- name: Check for image
  ansible.builtin.stat:
    path: "{{ libvirt_image_dir }}/{{ instance.name }}.qcow2"
  register: image_file

- name: Delete image (volume)
  ansible.builtin.shell: virsh vol-delete {{ instance.name }}.qcow2 --pool images
  become: true
  become_user: root
  when: image_file.stat.exists and instance.disk_image is not defined
  failed_when: false
  tags:
    - skip_ansible_lint

- name: Delete image (file)
  ansible.builtin.file:
    path: "{{ libvirt_image_dir }}/{{ instance.name }}.qcow2"
    state: absent
  become: true
  become_user: root
  when: image_file.stat.exists and instance.disk_image is defined
  failed_when: false

- name: Delete directory
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: absent
