---
- name: Include dependency
  ansible.builtin.include_tasks: dependency.yml
  when: provision_action == 'create'

- name: Create containers
  ansible.builtin.include_tasks: create.yml
  when: provision_action == 'create' and containers|length > 0

- name: Create virtual machines
  ansible.builtin.include_tasks: create_libvirt.yml
  when: provision_action == 'create' and virtual_machines|length > 0

- name: Destroy containers
  ansible.builtin.include_tasks: destroy.yml
  when: provision_action == 'destroy' and containers|length > 0

- name: Destroy virtual machines
  ansible.builtin.include_tasks: destroy_libvirt.yml
  when: provision_action == 'destroy' and virtual_machines|length > 0
