---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: fedora38
  - name: ubuntu2204
  - name: centos8
provisioner:
  name: ansible
verifier:
  name: ansible