ARG VERSION=12
FROM debian:$VERSION

ENV container=docker

STOPSIGNAL SIGRTMIN+3

RUN <<EOF
    apt update
    apt install -y systemd dbus openssh-server rsyslog ca-certificates sudo python3
    apt clean
EOF

#RUN sed -i 's/^\(module(load="imklog")\)/#\1/' /etc/rsyslog.conf

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

VOLUME /sys/fs/cgroup
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/sbin/init"]
