---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: "Include ansible_testing create"
      ansible.builtin.include_role:
        name: drpsychick.ansible_testing
      vars:
        action: 'create'

    - name: "Include ansible_testing destroy"
      ansible.builtin.include_role:
        name: drpsychick.ansible_testing
      vars:
        action: 'destroy'
