---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: ubuntu2204
  - name: fedora38
#  - name: debian11
provisioner:
  name: ansible
verifier:
  name: ansible
