---
- name: Install docker driver
  hosts: all
  tasks:
    - name: Install fuse-overlayfs
      package:
        name: fuse-overlayfs

- name: Install prerequisite docker
  hosts: all
  vars:
    docker_install_compose: false
    docker_daemon_options:
      storage-driver: "fuse-overlayfs"
      log-driver: "local"
      log-opts:
        max-size: "100m"
  roles:
    - geerlingguy.docker

- name: Install required packages
  hosts: all
  tasks:
    - name: Required packages
      ansible.builtin.package:
        name: "{{ ['python3-setuptools', 'python3-pip', 'python3-docker'] + (['openssh-client'] if ansible_distribution in ['Ubuntu','Debian'] else ['openssh-clients']) }}"
