---

- name: Install docker driver
  hosts: all
  tasks:
    - name: Update ansible
      ansible.builtin.shell: |
        ansible --version
        apt-get update
        apt-get upgrade -y ansible
      delegate_to: localhost
#      when: ansible_distribution == "Fedora"
#    - name: Fix dnf5 issue
#      ansible.builtin.shell: |
#        dnf install -y fuse-overlayfs
#      delegate_to: localhost
#      when: ansible_distribution == "Fedora"

    - name: Install fuse-overlayfs
      package:
        name: fuse-overlayfs
#      when: ansible_distribution != "Fedora"

- name: Install prerequisite docker
  hosts: all
  vars:
    docker_install_compose: false
    docker_daemon_options:
      storage-driver: "fuse-overlayfs"
      log-driver: "local"
      log-opts:
        max-size: "100m"
  roles:
    - geerlingguy.docker

- name: Install required packages
  hosts: all
  tasks:
    - name: Required packages
      ansible.builtin.package:
        name: "{{ ['python3-setuptools', 'python3-pip', 'python3-docker'] + (['openssh-client'] if ansible_distribution in ['Ubuntu','Debian'] else ['openssh-clients']) }}"
