name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # monthly on 30th, 03:15
    - cron: "15 3 30 * *"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Check docker config
        run: cat /etc/docker/daemon.json || echo; docker system info; docker version
      - name: Test
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}"
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_STDOUT_CALLBACK: "debug"
